# Generated by Django 4.2 on 2023-05-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('allergy_id', models.AutoField(db_column='Allergy_ID', primary_key=True, serialize=False)),
                ('allergen', models.CharField(db_column='Allergen', max_length=100)),
                ('reaction', models.CharField(db_column='Reaction', max_length=100)),
                ('severity', models.CharField(db_column='Severity', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(db_column='Diagnosis_ID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('description', models.TextField(db_column='Description')),
                ('code', models.CharField(db_column='Code', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImagingReport',
            fields=[
                ('report_id', models.AutoField(db_column='Report_ID', primary_key=True, serialize=False)),
                ('imaging_type', models.CharField(db_column='Imaging_Type', max_length=100)),
                ('report_date', models.DateField(db_column='Report_Date')),
                ('findings', models.TextField(db_column='Findings')),
                ('impression', models.TextField(db_column='Impression')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance_id', models.AutoField(db_column='Insurance_ID', primary_key=True, serialize=False)),
                ('insurance_provider_name', models.CharField(db_column='Insurance_Provider_Name', max_length=100)),
                ('policy_number', models.CharField(db_column='Policy_Number', max_length=100)),
                ('coverage_details', models.TextField(db_column='Coverage_Details')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('results_id', models.AutoField(db_column='Results_ID', primary_key=True, serialize=False)),
                ('test_name', models.CharField(db_column='Test_Name', max_length=100)),
                ('test_date', models.DateField(db_column='Test_Date')),
                ('result_value', models.CharField(db_column='Result_Value', max_length=100)),
                ('reference_range', models.CharField(db_column='Reference_Range', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.AutoField(db_column='Medication_ID', primary_key=True, serialize=False)),
                ('medication_name', models.CharField(db_column='Medication_Name', max_length=100)),
                ('dosage', models.CharField(db_column='Dosage', max_length=100)),
                ('frequency', models.CharField(db_column='Frequency', max_length=100)),
                ('duration', models.CharField(db_column='Duration', max_length=100)),
                ('instructions', models.TextField(db_column='Instructions')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(db_column='Patient_ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='First_Name', max_length=100)),
                ('last_name', models.CharField(db_column='Last_Name', max_length=100)),
                ('dob', models.DateField(db_column='DOB')),
                ('gender', models.CharField(db_column='Gender', max_length=10)),
                ('phone', models.CharField(db_column='Phone', max_length=20)),
                ('email', models.EmailField(db_column='Email', max_length=100)),
                ('address', models.CharField(db_column='Address', max_length=200)),
                ('medical_history', models.TextField(db_column='Medical_History', null=True)),
                ('allergies', models.ManyToManyField(db_column='Allergy', null=True, related_name='patients', to='website.allergy')),
                ('insurance_info', models.OneToOneField(db_column='Insurance_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='website.insurance')),
                ('medications', models.ManyToManyField(db_column='Medication', null=True, related_name='patients', to='website.medication')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(db_column='Provider_ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='First_Name', max_length=100)),
                ('last_name', models.CharField(db_column='Last_Name', max_length=100)),
                ('specialty', models.CharField(db_column='Specialty', max_length=100)),
                ('phone', models.CharField(db_column='Phone', max_length=20)),
                ('email', models.EmailField(db_column='Email', max_length=100)),
                ('address', models.CharField(db_column='Address', max_length=200)),
                ('organization', models.CharField(db_column='Organization', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='User_ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=100)),
                ('password', models.CharField(db_column='Password', max_length=100)),
                ('role', models.CharField(db_column='Role', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('vital_sign_id', models.AutoField(db_column='Vital_Sign_ID', primary_key=True, serialize=False)),
                ('measurement_date', models.DateField(db_column='Measurement_Date')),
                ('systolic_blood_pressure', models.IntegerField(db_column='Systolic_Blood_Pressure')),
                ('diastolic_blood_pressure', models.IntegerField(db_column='Diastolic_Blood_Pressure')),
                ('heart_rate', models.IntegerField(db_column='Heart_Rate')),
                ('respiratory_rate', models.IntegerField(db_column='Respiratory_Rate')),
                ('temperature', models.DecimalField(db_column='Temperature', decimal_places=1, max_digits=4)),
                ('patient', models.ForeignKey(db_column='Patient_ID', on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='website.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('procedure_id', models.AutoField(db_column='Procedure_ID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('description', models.TextField(db_column='Description')),
                ('code', models.CharField(db_column='Code', max_length=100)),
                ('patient', models.ForeignKey(db_column='Patient_ID', on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='website.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Message',
            fields=[
                ('message_id', models.AutoField(db_column='Message_ID', primary_key=True, serialize=False)),
                ('subject', models.CharField(db_column='Subject', max_length=100)),
                ('content', models.TextField(db_column='Content')),
                ('datetime', models.DateTimeField(db_column='DateTime')),
                ('receiver', models.ForeignKey(db_column='Receiver_ID', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='website.provider')),
                ('sender', models.ForeignKey(db_column='Sender_ID', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='website.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalEncounter',
            fields=[
                ('encounter_id', models.AutoField(db_column='Encounter_ID', primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(db_column='DateTime')),
                ('chief_complaint', models.CharField(db_column='Chief_Complaint', max_length=200)),
                ('diagnoses', models.ManyToManyField(db_column='Diagnosis_ID', related_name='medical_encounters', to='website.diagnosis')),
                ('imaging_reports', models.ManyToManyField(db_column='Report_ID', related_name='medical_encounters', to='website.imagingreport')),
                ('lab_results', models.ManyToManyField(db_column='Results_ID', related_name='medical_encounters', to='website.labresult')),
                ('medications', models.ManyToManyField(db_column='Medication_ID', related_name='medical_encounters', to='website.medication')),
                ('patient', models.ForeignKey(db_column='Patient_ID', on_delete=django.db.models.deletion.CASCADE, related_name='medical_encounters', to='website.patient')),
                ('procedures', models.ManyToManyField(db_column='Procedure_ID', related_name='medical_encounters', to='website.procedure')),
                ('provider', models.ForeignKey(db_column='Provider_ID', on_delete=django.db.models.deletion.CASCADE, related_name='medical_encounters', to='website.provider')),
                ('vital_signs', models.ManyToManyField(db_column='Vital_Sign_ID', related_name='medical_encounters', to='website.vitalsign')),
            ],
        ),
        migrations.AddField(
            model_name='labresult',
            name='patient',
            field=models.ForeignKey(db_column='Patient_ID', on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='website.patient'),
        ),
        migrations.AddField(
            model_name='imagingreport',
            name='patient',
            field=models.ForeignKey(db_column='Patient_ID', on_delete=django.db.models.deletion.CASCADE, related_name='imaging_reports', to='website.patient'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(db_column='Patient_ID', on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='website.patient'),
        ),
    ]
